version: "3.7"

services:

  flask:
    build: ./flask_app
    container_name: flask_app
    restart: on-failure
    environment:
      - APP_NAME=MyFlaskApp
    depends_on:
      - db
    links:
      - db
    expose:
      - 8080
    networks:
      app_net:
        ipv4_address: 192.168.0.4

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.5


  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    volumes:
    - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    links:
      - db
    ports:
      # external:internal
      # our computer : container
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  redis:
    container_name: redis
    image: redis

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1